name: linter

on:
    push:
        branches:
            - develop
            - main
    pull_request:
        branches:
            - develop
            - main

permissions:
    contents: write

jobs:
    quality:
        runs-on: ubuntu-latest
        environment: Testing
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'

            - name: Add Flux Credentials Loaded From ENV
              run: |
                  echo "Configuring Flux credentials..."
                  composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"
                  echo "Verifying credentials are set..."
                  composer config --list | grep -q "http-basic.composer.fluxui.dev" || exit 1
              # These secrets need to be added in your GitHub repository:
              # Go to Settings > Secrets and variables > Actions
              # Add FLUX_USERNAME and FLUX_LICENSE_KEY as repository secrets
              # Make sure the secrets are properly set in the environment settings
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
                  npm install

            - name: Run Pint
              run: vendor/bin/pint

            # - name: Commit Changes
            #   uses: stefanzweifel/git-auto-commit-action@v5
            #   with:
            #     commit_message: fix code style
            #     commit_options: '--no-verify'
            #     file_pattern: '!.github/workflows/* **/*'
